image: scorpil/rust:stable

test:
  script:
    - cargo test

pages:
  stage: deploy
  script:
    - cargo doc
    - mkdir public
    - cp -r target/doc/* public
    - cp misc/index.html public/
  artifacts:
    paths:
      - public
  only:
    - master

